# Generated by Django 5.1 on 2024-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AñoProyeccion', models.IntegerField()),
                ('Ingresos', models.FloatField()),
                ('NivelEducativo', models.IntegerField()),
                ('Edad', models.IntegerField()),
                ('Ocupacion', models.IntegerField()),
                ('AreaResidencia', models.IntegerField()),
                ('FrecuenciaReciclaje', models.IntegerField()),
                ('Televisor_Desechado', models.BooleanField(default=False)),
                ('Computadora_Desechado', models.BooleanField(default=False)),
                ('Baterías_Desechado', models.BooleanField(default=False)),
                ('TelefonoMovilBasico_Desechado', models.BooleanField(default=False)),
                ('ConsolaVideojuegos_Desechado', models.BooleanField(default=False)),
                ('Tablet_Desechado', models.BooleanField(default=False)),
                ('TelefonoMovilInteligente_Desechado', models.BooleanField(default=False)),
                ('ElectrodomesticosInteligentes_Desechado', models.BooleanField(default=False)),
                ('DispositivosDomotica_Desechado', models.BooleanField(default=False)),
                ('Otra_Desechado', models.BooleanField(default=False)),
            ],
        ),
    ]
