# Generated by Django 5.0.9 on 2024-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEntrenamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField()),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r2', models.FloatField()),
            ],
            options={
                'db_table': 'HistorialEntrenamientos',
            },
        ),
    ]
