# Generated by Django 5.1 on 2024-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos', models.FloatField()),
                ('edad', models.IntegerField()),
                ('dispositivos_adquiridos', models.IntegerField()),
                ('dispositivos_en_desuso', models.IntegerField()),
                ('tipo_dispositivo_reciclado', models.CharField(max_length=255)),
                ('tipo_dispositivo_desechado', models.CharField(max_length=255)),
            ],
        ),
    ]
